<a href="https://colab.research.google.com/github/syscrypto/Python-for-Data-Analysis/blob/main/Chapter04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics: Arrays and Vectorized Computation
- NumPy : Numerical Python의 줄임말로 Python에서 산술 계산에 필요한 필수 패키지
- 효율적인 다차원 배열 ndarray는 빠른 배열 계산과 브로드캐스팅 기능을 제공
- 반복문 작성없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수 제공
- 배열 데이터를 쓰거나 읽을 수 있ㄴ느 도구 와 메모리에 적재된 파일을 다루는 도구
- 선형대수, 난수 생성기, 푸리에 변환 기능 제공
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API

## Numpy ndarray : 다차원 배열 객체

In [ ]:
import numpy as np
# 임의의 값 생성
data = np.random.randn(2, 3)
data

array([[-1.17847438, -0.9878286 , -2.07168972],
       [ 1.19903045, -0.04574202, -0.49528079]])

In [ ]:
data + data

array([[-2.35694875, -1.97565719, -4.14337944],
       [ 2.39806091, -0.09148404, -0.99056158]])

In [ ]:
data*10

array([[-11.78474376,  -9.87828595, -20.71689721],
       [ 11.99030455,  -0.4574202 ,  -4.9528079 ]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

### ndarray 생성

In [ ]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
ar = np.ones(5)
ar

array([1., 1., 1., 1., 1.])

In [ ]:
ar.dtype

dtype('float64')

In [ ]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Data Types for ndarrays
- The data type or dtype is special object containing the information(or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data.

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
arr2.dtype

float64


dtype('int32')

In [ ]:
arr1

array([1., 2., 3.])

In [ ]:
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr.dtype

[1 2 3 4 5]


dtype('int64')

- astype method를 사용해서 배열의 dtype을 다른형으로 변환(casting)가능

In [ ]:
float_arr = arr.astype(np.float64)
print(float_arr)
float_arr.dtype

[1. 2. 3. 4. 5.]


dtype('float64')

- float64 -> int32 로 변환(convert or cast)

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

print(int_array.astype(calibers.dtype))
print(calibers.dtype)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


### Arithmetic with Numpy Arrays
- for문을 사용하지 않고 data를 처리함 이를 Vectorization 이라함
- array 연산은 equal-size arrays 에 가능

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
#arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

- Broadcasting : 크기가 다른 배열간의 연산

## Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)

arr[5:9]

array([5, 6, 7, 8])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr_copy = arr[5:8].copy(), arr[0:2].copy()

In [ ]:
arr_copy

(array([64, 64, 64]), array([0, 1]))

### Transposing Arrays and Swapping Axes

In [ ]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr = np.random.randn(6, 3)
arr

array([[ 1.44948839,  0.58907481,  0.93290798],
       [-1.8606575 ,  3.13996357,  0.51577281],
       [ 1.28802134, -0.28856379,  0.31879012],
       [ 0.93492075,  0.32248247,  1.39836779],
       [-0.16940067, -0.55772177, -0.77161558],
       [-1.62004345, -0.71939266,  0.14150306]])

In [ ]:
np.dot(arr.T, arr)

array([[10.74937608, -3.79879463,  2.01200538],
       [-3.79879463, 11.22222376,  2.85656878],
       [ 2.01200538,  2.85656878,  3.80881222]])